version: '3.8'
services:

  service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "15432:5432"
    restart: unless-stopped
    networks:
      - my-network

  client-backend:
    depends_on:
      - service-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/docker
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
